# Generated by Django 4.1.4 on 2022-12-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('country_id', models.CharField(max_length=1)),
                ('product_id', models.CharField(max_length=6)),
                ('factory_id', models.CharField(max_length=6)),
            ],
        ),
    ]
